import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  LucideProps,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  Twitter,
  User,
  UserRound,
  X,
  BotIcon,
  FolderClosed,
  LayoutDashboard,
  LucideIcon,
  MessageSquare,
  MessagesSquare,
  Key,
  Coins,
  ArrowUp,
  CheckCheck,
  ArrowDown,
  Import,
  BadgePlus,
  Copy,
  Download,
  Send,
  Loader,
  RefreshCcw,
  Paperclip,
  Lock,
  Calendar,
  Phone,
  Mail,
  Speech,
  Brain,
  Eye,
  Codepen,
  Facebook,
  Instagram,
  Clock,
  Circle,
  Info,
  Search,
  Play,
  Pause,
  Cog,
  MessageSquareHeart,
} from "lucide-react";

// Import the custom Google icon from Material UI
import GoogleIcon from "@mui/icons-material/Google";

export type Icon = LucideIcon;

export const Icons = {
  // Lucide Icons
  lock: Lock,
  document: File,
  paperclip: Paperclip,
  reload: RefreshCcw,
  loading: Loader,
  send: Send,
  download: Download,
  copy: Copy,
  badgeplus: BadgePlus,
  import: Import,
  logo: Command,
  folder: FolderClosed,
  dashboard: LayoutDashboard,
  close: X,
  key: Key,
  checkcheck: CheckCheck,
  coin: Coins,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  bot: BotIcon,
  warning: AlertTriangle,
  user: User,
  userRound: UserRound,
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  message: MessageSquare,
  messagesSquare: MessagesSquare,
  calendar: Calendar,
  phone: Phone,
  mail: Mail,
  speech: Speech,
  brain: Brain,
  eye: Eye,
  codepen: Codepen,
  facebook: Facebook,
  instagram: Instagram,
  clock: Clock,
  circle: Circle,
  info: Info,
  search: Search,
  play: Play,
  pause: Pause,
  cog: Cog,
  messageSquareHeart: MessageSquareHeart,
  userRound: UserRound,
  // Custom Imported Icons
  google: GoogleIcon, // Custom Google icon added here
};
