import { siteConfig } from '@/config/site'
import { twMerge } from 'tailwind-merge'
import { getSafeGitHubConfig } from "@/lib/utils"

export const dynamic = 'force-dynamic';

export default function ChangelogPage() {
    // Add safe GitHub config
    const safeConfig = getSafeGitHubConfig();
    
    return (
        <div className="w-full flex flex-col items-center">
            <div className="w-full text-center p-8 pb-24">
                <h1 className="w-full text-lg">Changelog</h1>
                <p className="w-full text-4xl text-neutral-500 mt-3">
                    What&apos;s new in {siteConfig.name}?
                </p>
            </div>
            <div className="p-4 max-w-screen-sm">
                <Release
                    isFirst={true}
                    version="0.3.1"
                    date="2024-08-06"
                    improvements={[
                        {
                            title: 'Fix issue when downloading file generated by assistant',
                            description: 'Fix issue when downloading file generated by assistant. Now the file will be downloaded correctly.',
                        }
                    ]}
                />
                <Release
                    version="0.3.0"
                    date="2024-08-05"
                    new={[
                        {
                            title: 'Chatbot Embed',
                            description: 'You can now embed your chatbot on your website. Go to your chatbot settings and click on "Embed" to get the code.',
                        }
                    ]}
                />
                <Release
                    version="0.2.0"
                    date="2024-08-01"
                    new={[
                        {
                            title: 'Chatbot Customization',
                            description: 'You can now customize your chatbot with your own logo, colors, and more. Go to your chatbot settings to customize it.',
                        }
                    ]}
                />
                <Release
                    version="0.1.0"
                    date="2024-07-15"
                    new={[
                        {
                            title: 'Initial Release',
                            description: 'First version of the platform with basic chatbot functionality.',
                        }
                    ]}
                />
            </div>
        </div>
    )
}

function Release(props: { isFirst?: boolean; version: string; date: string; new?: any[]; improvements?: any[]; bugs?: any[] }) {
    return (
        <div
            className={twMerge(
                'flex flex-col gap-4 border-t pt-4 mt-8',
                props.isFirst && 'border-t-0 mt-0',
            )}
        >
            <div>
                <div className="font-bold text-3xl">
                    Version <span className="">{props.version}</span>
                </div>
                <div className="text-neutral-500 font-semibold">{props.date}</div>
            </div>
            {props.new && (
                <div className="grid grid-cols-1 gap-3">
                    <span className="font-semibold text-xs uppercase bg-emerald-500 border border-emerald-600 text-white px-1.5 py-0.5 rounded w-fit">
                        New
                    </span>
                    <div className="flex flex-col gap-2">
                        {props.new?.map((item, index) => (
                            <div className="mb-2" key={`new-${index}`}>
                                <div className="font-bold pb-1 text-base">🎉 {item.title}</div>
                                <div className="text-neutral-500 text-sm pb-3">
                                    {item.description}
                                </div>
                                {item.image && (
                                    <img
                                        src={item.image}
                                        className="w-2/3 rounded shadow border mb-2"
                                        alt={item.title}
                                    />
                                )}
                            </div>
                        ))}
                    </div>
                </div>
            )}
            {props.improvements && (
                <div className="grid grid-cols-1 gap-3">
                    <span className="font-semibold text-xs uppercase bg-blue-500 border border-blue-600 text-white px-1.5 py-0.5 rounded w-fit">
                        Improvements
                    </span>
                    <div className="flex flex-col gap-2">
                        {props.improvements?.map((item, index) => (
                            <div className="mb-2" key={`improvements-${index}`}>
                                <div className="font-bold pb-1 text-base">🚀 {item.title}</div>
                                <div className="text-neutral-500 text-sm pb-3">
                                    {item.description}
                                </div>
                                {item.image && (
                                    <img
                                        src={item.image}
                                        className="w-2/3 rounded shadow border mb-2"
                                        alt={item.title}
                                    />
                                )}
                            </div>
                        ))}
                    </div>
                </div>
            )}
            {props.bugs && (
                <div className="grid grid-cols-1 gap-3">
                    <span className="font-semibold text-xs uppercase bg-rose-500 border border-rose-600 text-white px-1.5 py-0.5 rounded w-fit">
                        Bugs
                    </span>
                    <div className="flex flex-col gap-2">
                        {props.bugs?.map((item, index) => (
                            <div className="mb-2" key={`bugs-${index}`}>
                                <div className="font-bold pb-1 text-base">🐛 {item.title}</div>
                                <div className="text-neutral-500 text-sm pb-3">
                                    {item.description}
                                </div>
                                {item.image && (
                                    <img
                                        src={item.image}
                                        className="w-2/3 rounded shadow border mb-2"
                                        alt={item.title}
                                    />
                                )}
                            </div>
                        ))}
                    </div>
                </div>
            )}
        </div>
    )
}
